-- Family Heritage Tree V5 - Supabase schema
-- Run this file once in the Supabase SQL Editor.
-- IMPORTANT: replace YOUR_ADMIN_EMAIL_HERE near the bottom before running that line.

create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.family_admins (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.family_snapshots (
  id uuid primary key default gen_random_uuid(),
  version bigint generated by default as identity unique,
  data jsonb not null,
  note text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  created_by_email text default (auth.jwt() ->> 'email')
);

create table if not exists public.family_submissions (
  id uuid primary key default gen_random_uuid(),
  person_id text,
  kind text not null default 'other',
  details text not null,
  payload jsonb not null default '{}'::jsonb,
  submitter_name text,
  submitter_contact text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  reviewer_note text
);

create table if not exists public.family_audit_log (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  actor_id uuid default auth.uid(),
  actor_email text default (auth.jwt() ->> 'email'),
  created_at timestamptz not null default now()
);

create or replace function private.is_family_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.family_admins a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function private.is_family_admin() from public;
grant execute on function private.is_family_admin() to authenticated;

alter table public.family_admins enable row level security;
alter table public.family_snapshots enable row level security;
alter table public.family_submissions enable row level security;
alter table public.family_audit_log enable row level security;

revoke all on public.family_admins from anon, authenticated;
revoke all on public.family_snapshots from anon, authenticated;
revoke all on public.family_submissions from anon, authenticated;
revoke all on public.family_audit_log from anon, authenticated;

grant select on public.family_admins to authenticated;
grant select on public.family_snapshots to anon, authenticated;
grant insert, update, delete on public.family_snapshots to authenticated;
grant insert on public.family_submissions to anon, authenticated;
grant select, update, delete on public.family_submissions to authenticated;
grant select, insert on public.family_audit_log to authenticated;

-- Admin can confirm their own allow-list row after signing in.
drop policy if exists "admins can read own admin row" on public.family_admins;
create policy "admins can read own admin row"
on public.family_admins for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- Anyone may read only the published family snapshot.
drop policy if exists "public can read published snapshots" on public.family_snapshots;
create policy "public can read published snapshots"
on public.family_snapshots for select
to anon
using (is_published = true);

drop policy if exists "authenticated can read published or admin snapshots" on public.family_snapshots;
create policy "authenticated can read published or admin snapshots"
on public.family_snapshots for select
to authenticated
using (is_published = true or private.is_family_admin());

drop policy if exists "admins can insert snapshots" on public.family_snapshots;
create policy "admins can insert snapshots"
on public.family_snapshots for insert
to authenticated
with check (private.is_family_admin());

drop policy if exists "admins can update snapshots" on public.family_snapshots;
create policy "admins can update snapshots"
on public.family_snapshots for update
to authenticated
using (private.is_family_admin())
with check (private.is_family_admin());

drop policy if exists "admins can delete snapshots" on public.family_snapshots;
create policy "admins can delete snapshots"
on public.family_snapshots for delete
to authenticated
using (private.is_family_admin());

-- Family members can submit corrections without seeing anybody else's submissions.
drop policy if exists "public can submit family corrections" on public.family_submissions;
create policy "public can submit family corrections"
on public.family_submissions for insert
to anon
with check (status = 'pending' and reviewed_at is null and reviewed_by is null);

drop policy if exists "authenticated can submit family corrections" on public.family_submissions;
create policy "authenticated can submit family corrections"
on public.family_submissions for insert
to authenticated
with check (status = 'pending' and reviewed_at is null and reviewed_by is null);

drop policy if exists "admins can read submissions" on public.family_submissions;
create policy "admins can read submissions"
on public.family_submissions for select
to authenticated
using (private.is_family_admin());

drop policy if exists "admins can review submissions" on public.family_submissions;
create policy "admins can review submissions"
on public.family_submissions for update
to authenticated
using (private.is_family_admin())
with check (private.is_family_admin());

drop policy if exists "admins can delete submissions" on public.family_submissions;
create policy "admins can delete submissions"
on public.family_submissions for delete
to authenticated
using (private.is_family_admin());

-- Audit history is private to admins.
drop policy if exists "admins can read audit log" on public.family_audit_log;
create policy "admins can read audit log"
on public.family_audit_log for select
to authenticated
using (private.is_family_admin());

drop policy if exists "admins can write audit log" on public.family_audit_log;
create policy "admins can write audit log"
on public.family_audit_log for insert
to authenticated
with check (private.is_family_admin());

-- Approved family media is stored in a public bucket. Only authenticated admins can upload/change files.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'family-media',
  'family-media',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/heic']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "family admins can read media metadata" on storage.objects;
create policy "family admins can read media metadata"
on storage.objects for select
to authenticated
using (bucket_id = 'family-media' and private.is_family_admin());

drop policy if exists "family admins can upload media" on storage.objects;
create policy "family admins can upload media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'family-media' and private.is_family_admin());

drop policy if exists "family admins can update media" on storage.objects;
create policy "family admins can update media"
on storage.objects for update
to authenticated
using (bucket_id = 'family-media' and private.is_family_admin())
with check (bucket_id = 'family-media' and private.is_family_admin());

drop policy if exists "family admins can delete media" on storage.objects;
create policy "family admins can delete media"
on storage.objects for delete
to authenticated
using (bucket_id = 'family-media' and private.is_family_admin());

-- FIRST ADMIN SETUP
-- 1) Replace the email below with the email you will use for Supabase magic-link login.
-- 2) Run this line in the SQL Editor after the tables/policies above exist.
-- insert into public.family_admins(email) values ('YOUR_ADMIN_EMAIL_HERE') on conflict do nothing;

-- Recommended indexes
create index if not exists family_snapshots_published_version_idx
  on public.family_snapshots (is_published, version desc);
create index if not exists family_submissions_status_created_idx
  on public.family_submissions (status, created_at desc);
create index if not exists family_submissions_person_idx
  on public.family_submissions (person_id);
