const familyData = {
  rootTrail: [
    {type:'person',id:'nayer-chowdhury',en:'Nayer Chowdhury',bn:'নায়ের চৌধুরী',noteEn:'Landlord; earliest named ancestor in the record.',noteBn:'জমিদার; নথিতে উল্লেখিত প্রাচীনতম নাম।'},
    {type:'missing',en:'One intermediary generation is not recorded',bn:'মাঝখানের একটি প্রজন্মের নাম নথিভুক্ত নেই'},
    {type:'person',id:'chan-gazi-hawladar',en:'Chan Gazi Hawladar',bn:'চাঁন গাজী হাওলাদার',noteEn:'Recorded ancestor and father of Mohabbat Ali Munsir and Abdullah Chamra.',noteBn:'মোহাব্বত আলি মুনসির ও আব্দুল্লাহ চামড়ার পিতা।'}
  ],
  main: {
    id:'mohabbat-ali-munsir',en:'Mohabbat Ali Munsir',bn:'মোহাব্বত আলি মুনসির',noteEn:'Main family branch • 4 sons and 2 daughters recorded.',noteBn:'প্রধান পারিবারিক শাখা • ৪ ছেলে ও ২ মেয়ে নথিভুক্ত।',
    children:[
      {id:'noor-mia',en:'Noor Mia',bn:'নূর মিয়া',noteEn:'4 sons and 2 daughters recorded.',noteBn:'৪ ছেলে ও ২ মেয়ে নথিভুক্ত।',children:[
        {id:'abul-khayer',en:'Abul Khayer (Qari Saheb)',bn:'আবুল খায়ের (কারী সাহেব)',children:[
          {id:'ibrahim-boro-boba',en:'Ibrahim (Boro Boba)',bn:'ইব্রাহিম (বড় বোবা)'},{id:'yusuf-maijja-boba',en:'Yusuf (Maijja Boba)',bn:'ইউসুফ (মাইজ্যা বোবা)'},{id:'belal',en:'Belal',bn:'বেলাল'},{id:'milon',en:'Milon',bn:'মিলন'},{id:'sefu',en:'Sefu',bn:'সেফু'},{id:'kusum',en:'Kusum',bn:'কুসুম',relationEn:'Daughter',relationBn:'মেয়ে'}]},
        {id:'choiyeed-ahmed',en:'Choiyeed Ahmed',bn:'ছৈইয়দ আহমেদ',children:[
          {id:'dulal-ahmed',en:'Dulal Ahmed',bn:'দুলাল আহমেদ'},{id:'anowar-son-choiyeed',en:'Anowar',bn:'আনোয়ার'},{id:'delowar',en:'Delowar',bn:'দেলোয়ার'},{id:'lokman',en:'Lokman',bn:'লকমান'},{id:'khokon-choiyeed',en:'Khokon',bn:'খোকন'},{id:'mayan',en:'Mayan',bn:'মায়ান',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'amena',en:'Amena',bn:'আমেনা',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'lilu',en:'Lilu',bn:'লিলু',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'jahanara-janu',en:'Jahanara Janu',bn:'জাহানারা জানু',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'sahin-daughter-choiyeed',en:'Sahin',bn:'সাহিন',relationEn:'Daughter',relationBn:'মেয়ে'}]},
        {id:'mofizur-rahman',en:'Mofizur Rahman',bn:'মোফিজুর রহমান',children:[
          {id:'saifur-rahman-tipu',en:'Saifur Rahman Tipu',bn:'সাইফুর রহমান টিপু'},{id:'mizanur-rahman-tulu',en:'Mizanur Rahman Tulu',bn:'মিজানুর রহমান টুলু'},{id:'arifur-rahman-tiku',en:'Arifur Rahman Tiku',bn:'আরিফুর রহমান টিকু'},{id:'russell',en:'Russell',bn:'রাসেল'},{id:'mukti',en:'Mukti',bn:'মুক্তি',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'mary',en:'Mary',bn:'মেরি',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'munni',en:'Munni',bn:'মুন্নি',relationEn:'Daughter',relationBn:'মেয়ে'}]},
        {id:'mominul-islam',en:'Mominul Islam',bn:'মোমিনুল ইসলাম',noteEn:'3 sons recorded; only Piyas is named in the supplied record.',noteBn:'৩ ছেলে নথিভুক্ত; প্রদত্ত নথিতে শুধু পিয়াসের নাম উল্লেখ আছে।',children:[
          {id:'piyas',en:'Piyas',bn:'পিয়াস',deceased:true},{id:'mominul-unknown-son-1',en:'Son — name not recorded',bn:'ছেলে — নাম নথিভুক্ত নেই',placeholder:true},{id:'mominul-unknown-son-2',en:'Son — name not recorded',bn:'ছেলে — নাম নথিভুক্ত নেই',placeholder:true}]}
      ]},
      {id:'anowar-ullah',en:'Anowar Ullah',bn:'আনোয়ার উল্লাহ',noteEn:'3 wives recorded.',noteBn:'৩ জন স্ত্রী নথিভুক্ত।',spouseGroups:[
        {spouseEn:'First wife — name not recorded',spouseBn:'প্রথম স্ত্রী — নাম নথিভুক্ত নেই',statusEn:'Deceased',statusBn:'মৃত্যুবরণ করেছেন',children:[]},
        {spouseEn:'Second wife — name not recorded',spouseBn:'দ্বিতীয় স্ত্রী — নাম নথিভুক্ত নেই',children:[
          {id:'siddik-ullah',en:'Siddik Ullah',bn:'সিদ্দিক উল্লাহ',children:[{id:'mahfuzur-rahman',en:'Mahfuzur Rahman',bn:'মাহফুজুর রহমান'},{id:'zilkarnain-khokon',en:'Zilkarnain Khokon',bn:'জিলকারনাইন খোকন'},{id:'parvin',en:'Parvin',bn:'পারভিন',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'sahin-siddik',en:'Sahin',bn:'সাহিন',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'nasrin',en:'Nasrin',bn:'নাসরিন',relationEn:'Daughter',relationBn:'মেয়ে'}]},
          {id:'nur-jahan-anowar',en:'Nur Jahan',bn:'নূর জাহান',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'tara-begum',en:'Tara Begum',bn:'তারা বেগম',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'hosenara',en:'Hosenara',bn:'হোসেনআরা',relationEn:'Daughter',relationBn:'মেয়ে'}]},
        {spouseEn:'Third wife — name not recorded',spouseBn:'তৃতীয় স্ত্রী — নাম নথিভুক্ত নেই',children:[{id:'leda',en:'Leda',bn:'লেদা',noteEn:'Recorded as disabled.',noteBn:'নথিতে প্রতিবন্ধী হিসেবে উল্লেখ।'},{id:'salema',en:'Salema',bn:'সালেমা',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'rezia',en:'Rezia',bn:'রেজিয়া',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'sufia-begum-moni',en:'Sufia Begum Moni',bn:'সুফিয়া বেগম মনি',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'noni',en:'Noni',bn:'ননি',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'kohinur-mukta',en:'Kohinur Mukta',bn:'কহিনুর মুক্তা',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'manik',en:'Manik',bn:'মানিক',relationEn:'Daughter',relationBn:'মেয়ে'}]}
      ]},
      {id:'afaz-mia',en:'Afaz Mia',bn:'আফাজ মিয়া',children:[
        {id:'abdul-haq',en:'Abdul Haq',bn:'আবদুল হক',children:[{id:'abdur-nur-babul',en:'Abdur Nur (Babul)',bn:'আব্দুর নূর (বাবুল)'},{id:'abdul-odud-bacchu',en:'Abdul Odud Bacchu',bn:'আব্দুল ওদুদ বাচ্চু'},{id:'golam-nur-sahin',en:'Golam Nur Sahin',bn:'গোলাম নূর সাহিন'},{id:'mozammel-hosen-didar',en:'Mozammel Hosen Didar',bn:'মোজাম্মেল হোসেন দিদার'},{id:'nazmul-hosen',en:'Nazmul Hosen',bn:'নাজমুল হোসেন'},{id:'ayesha',en:'Ayesha',bn:'আয়েশা',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'maya-afaz',en:'Maya',bn:'মায়া',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'tahura',en:'Tahura',bn:'তাহুরা',relationEn:'Daughter',relationBn:'মেয়ে'}]},
        {id:'piyara-begum-ledi',en:'Piyara Begum Ledi',bn:'পেয়ারা বেগম লেদি',relationEn:'Daughter',relationBn:'মেয়ে'}]},
      {id:'dr-abul-hasem',en:'Dr. Abul Hasem',bn:'ডাঃ আবুল হাসেম',spouses:[{en:'Sadia Khatun',bn:'সাদিয়া খাতুন'}],noteEn:'5 sons and 5 daughters recorded.',noteBn:'৫ ছেলে ও ৫ মেয়ে নথিভুক্ত।',children:[
        {id:'rafiqul-islam',en:'Rafiqul Islam',bn:'রফিকুল ইসলাম',spouses:[{en:'Jahanara Begum',bn:'জাহানারা বেগম'}],children:[{id:'saiful-islam-sobor',en:'Saiful Islam Sobor',bn:'সাইফুল ইসলাম সোবর'},{id:'shariful-islam-palash',en:'Shariful Islam Palash',bn:'শরিফুল ইসলাম পলাশ'},{id:'rezaul-islam-peter',en:'Rezaul Islam Peter',bn:'রেজাউল ইসলাম পিটার'},{id:'redwanul-islam-muna',en:'Redwanul Islam Muna',bn:'রেদওয়ানুল ইসলাম মুনা'},{id:'mihiron',en:'Mihiron',bn:'মিহিরন'}]},
        {id:'shahidul-islam',en:'Shahidul Islam',bn:'শহিদুল ইসলাম',spouses:[{en:'Rehana Begum',bn:'রেহানা বেগম'}],children:[{id:'tahamina-akter-pinu',en:'Tahamina Akter Pinu',bn:'তাহামিনা আক্তার পিনু'},{id:'sheikh-farid',en:'Sheikh Farid',bn:'শেখ ফরিদ'},{id:'harunur-rashid-toha',en:'Harunur Rashid Toha',bn:'হারুনুর রশিদ তোহা'}]},
        {id:'golam-mostofa',en:'Golam Mostofa',bn:'গোলাম মোস্তফা',spouses:[{en:'Jesmin',bn:'জেসমিন',statusEn:'Divorced',statusBn:'ডিভোর্স'},{en:'Mahbuba Akter Josna',bn:'মাহবুবা আক্তার জোসনা'}],children:[{id:'mahbub-alam-mamun',en:'Mahbub Alam Mamun',bn:'মাহবুব আলম মামুন'},{id:'nure-alam-tahamim',en:'Nure Alam Tahamim',bn:'নূরে আলম তাহামিম'},{id:'ajmeri-sultana-afsana',en:'Ajmeri Sultana Afsana',bn:'আজমেরী সুলতানা আফসানা',deceased:true,noteEn:'Died at age 11.',noteBn:'১১ বছর বয়সে মৃত্যুবরণ।'}]},
        {id:'amir-hosen',en:'Amir Hosen',bn:'আমির হোসেন',spouses:[{en:'Hajera Begum Ruby',bn:'হাজেরা বেগম রুবি'}],children:[{id:'israt-jahan-rumana',en:'Israt Jahan Rumana',bn:'ইসরাত জাহান রুমানা'},{id:'sanjana-jahan-mim',en:'Sanjana Jahan Mim',bn:'সানজানা জাহান মিম'}]},
        {id:'mohammad-ali-jinnah',en:'Mohammad Ali Jinnah',bn:'মোহাম্মদ আলী জিন্নাহ',spouses:[{en:'Nazma Begum',bn:'নাজমা বেগম'}],children:[{id:'md-al-amin',en:'Md. Al Amin',bn:'মোঃ আল আমিন'},{id:'sharmin-sultana',en:'Sharmin Sultana',bn:'শারমিন সুলতানা'},{id:'md-zillur-rahman-saimun',en:'Md. Zillur Rahman Saimun',bn:'মোঃ জিল্লুর রহমান সাইমুন',relationEn:'You',relationBn:'আপনি'},{id:'md-mehdi-hasan-sifat',en:'Md. Mehdi Hasan Sifat',bn:'মোঃ মেহদী হাসান সিফাত'}]},
        {id:'monowara-begum',en:'Monowara Begum',bn:'মনোয়ারা বেগম',relationEn:'Daughter',relationBn:'মেয়ে',noteEn:'One daughter is recorded, but her name is not confirmed in the supplied document.',noteBn:'এক কন্যা নথিভুক্ত, তবে প্রদত্ত নথিতে তার নাম নিশ্চিত নয়।',children:[{id:'monowara-unknown-daughter',en:'Daughter — name to confirm',bn:'কন্যা — নাম নিশ্চিত করা বাকি',placeholder:true}]},
        {id:'anowara-begum',en:'Anowara Begum',bn:'আনোয়ারা বেগম',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Abdur Nur',bn:'আব্দুর নূর'}],children:[{id:'jahid-nur-tapan',en:'Jahid Nur Tapan',bn:'জাহিদ নূর তপন'},{id:'jesmin-akter-baby',en:'Jesmin Akter Baby',bn:'জেসমিন আক্তার বেবি'},{id:'shahid-nur-ripon',en:'Shahid Nur Ripon',bn:'শহিদ নূর রিপন'},{id:'abid-nur-babu',en:'Abid Nur Babu',bn:'আবিদ নূর বাবু'}]},
        {id:'shamsun-nahar-nani',en:'Shamsun Nahar Nani',bn:'শামসুন নাহার ননি',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Golam Mostofa',bn:'গোলাম মোস্তফা'}],children:[{id:'sahajan-parvin-pakhi',en:'Sahajan Parvin Pakhi',bn:'সাহাজান পারভীন পাখি'},{id:'laki',en:'Laki',bn:'লাকি'},{id:'salauddin-roni',en:'Salauddin Roni',bn:'সালাউদ্দিন রনি'},{id:'raiha-binte-moumumi',en:'Raiha Binte Moumumi',bn:'রাইহা বিনতে মৌমুমি'},{id:'akhi',en:'Akhi',bn:'আখি'}]},
        {id:'nurjahan-nur',en:'Nurjahan Nur',bn:'নূরজাহান নূর',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Mohammad Ullah',bn:'মোহাম্মদ উল্লাহ'}],children:[{id:'sohel-rana',en:'Sohel Rana',bn:'সোহেল রানা'},{id:'rumi',en:'Rumi',bn:'রুমি'},{id:'sarmin-akter-rumi',en:'Sarmin Akter Rumi',bn:'সারমিন আক্তার রুমি'},{id:'rubel',en:'Rubel',bn:'রুবেল'},{id:'rahima-akter-poly',en:'Rahima Akter Poly',bn:'রহিমা আক্তার পলি'}]},
        {id:'fatema-begum',en:'Fatema Begum',bn:'ফাতেমা বেগম',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Mizanur Rahman',bn:'মিজানুর রহমান'}],children:[{id:'asma-rahman',en:'Asma Rahman',bn:'আসমা রহমান'},{id:'asifur-rahman',en:'Asifur Rahman',bn:'আসিফুর রহমান'}]}
      ]},
      {id:'rati',en:'Rati',bn:'রাতি',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Husband — name unknown',bn:'স্বামী — নাম অজানা'}]},
      {id:'akuri',en:'Akuri',bn:'আঃকুরি',relationEn:'Daughter',relationBn:'মেয়ে',spouses:[{en:'Husband — name unknown',bn:'স্বামী — নাম অজানা'}]}
    ]
  },
  secondary:{id:'abdullah-chamra',en:'Abdullah Chamra',bn:'আব্দুল্লাহ চামড়া',noteEn:'Related branch • kept visually smaller to distinguish it from the Mohabbat Ali Munsir branch.',noteBn:'সম্পর্কিত শাখা • মোহাব্বত আলি মুনসির শাখা থেকে আলাদা বোঝাতে তুলনামূলক ছোটভাবে দেখানো হয়েছে।',children:[
    {id:'yunus-mia',en:'Yunus Mia',bn:'ইউনুস মিয়া',spouseGroups:[{spouseEn:'First wife — name not recorded',spouseBn:'প্রথম স্ত্রী — নাম নথিভুক্ত নেই',statusEn:'Deceased',statusBn:'মৃত্যুবরণ করেছেন',children:[{id:'safik-ur-rahman-chamra',en:'Safik Ur Rahman (Chamra)',bn:'সফিক উর রহমান (চামড়া)'}]},{spouseEn:'Second wife — name not recorded',spouseBn:'দ্বিতীয় স্ত্রী — নাম নথিভুক্ত নেই',children:[{id:'nur-nabi',en:'Nur Nabi',bn:'নূর নবী'},{id:'afsana-yunus',en:'Afsana',bn:'আফসানা',relationEn:'Daughter',relationBn:'মেয়ে'}]}]},
    {id:'haydar-ali',en:'Haydar Ali',bn:'হায়দার আলী',children:[{id:'alam-haydar',en:'Alam',bn:'আলাম'},{id:'babul-haydar',en:'Babul',bn:'বাবুল'},{id:'haydar-daughter-1',en:'Daughter — name not recorded',bn:'মেয়ে — নাম নথিভুক্ত নেই',placeholder:true},{id:'haydar-daughter-2',en:'Daughter — name not recorded',bn:'মেয়ে — নাম নথিভুক্ত নেই',placeholder:true},{id:'haydar-daughter-3',en:'Daughter — name not recorded',bn:'মেয়ে — নাম নথিভুক্ত নেই',placeholder:true}]},
    {id:'yusuf-ali',en:'Yusuf Ali',bn:'ইউসুফ আলী',children:[{id:'lalu-mia',en:'Lalu Mia',bn:'লালু মিয়া'},{id:'abul-kashem',en:'Abul Kashem',bn:'আবুল কাসেম'},{id:'abul-kalam',en:'Abul Kalam',bn:'আবুল কালাম'},{id:'akub-ali',en:'Akub Ali',bn:'একুব আলী'},{id:'jahir',en:'Jahir',bn:'জহির'},{id:'rosen',en:'Rosen',bn:'রোসেন',relationEn:'Daughter',relationBn:'মেয়ে'},{id:'halima',en:'Halima',bn:'হালিমা',relationEn:'Daughter',relationBn:'মেয়ে'}]},
    {id:'ramar-bap',en:'Ramar Bap',bn:'রমার বাপ'},{id:'badiyar-bap',en:'Badiyar Bap',bn:'বদিয়ার বাপ'},{id:'ruhul-amin-er-bap',en:'Father of Ruhul Amin',bn:'রুহুল আমিন এর বাপ'}
  ]}
};

const translations={
 en:{brandTitle:'Family Heritage Tree',brandSub:'Nayer Chowdhury lineage',expandAll:'Expand all',collapseAll:'Collapse all',eyebrow:'Family gathering edition',heroTitle:'Our Family Heritage',heroText:'A clear, bilingual family tree showing who belongs to which branch, spouses, children and later generations.',searchLabel:'Search family member',searchPlaceholder:'Search any name…',clear:'Clear',sourceNote:'Compiled from the family lineage document and the corrections supplied in this chat. Unknown or unrecorded names are clearly marked instead of guessed.',ancestralRoot:'Ancestral root',startingPoint:'Starting point of the recorded lineage',mainBranch:'Main branch',primaryFocus:'Primary display',secondBranch:'Related branch',compactBranch:'Compact branch',howToRead:'How to read this tree',guideTitle:'Every card tells you exactly where a person belongs.',guideParent:'Connector',guideParentText:'The line above a card points to that person’s parent.',guideSpouse:'Spouse',guideSpouseText:'Spouses are listed inside the same family card, including multiple marriages when recorded.',guideGeneration:'Generation colour',guideGenerationText:'People at the same family-tree depth share the same colour.',footerText:'Family Heritage Tree • Built for the family gathering',showChildren:'Show children',hideChildren:'Hide children',generation:'Generation',deceased:'Deceased',noResults:'No matching family member found.',branchTitleMain:'Mohabbat Ali Munsir family',branchTitleSecondary:'Abdullah Chamra family'},
 bn:{brandTitle:'পারিবারিক বংশ পরিচয়',brandSub:'নায়ের চৌধুরীর বংশধারা',expandAll:'সব খুলুন',collapseAll:'সব বন্ধ করুন',eyebrow:'পারিবারিক মিলনমেলা সংস্করণ',heroTitle:'আমাদের পারিবারিক বংশধারা',heroText:'কে কোন শাখার, কার স্ত্রী/স্বামী কে, কার সন্তান কারা এবং পরবর্তী প্রজন্ম—সবকিছু পরিষ্কারভাবে দেখানো দ্বিভাষিক পারিবারিক বৃক্ষ।',searchLabel:'পরিবারের সদস্য খুঁজুন',searchPlaceholder:'যেকোনো নাম খুঁজুন…',clear:'মুছুন',sourceNote:'পারিবারিক বংশ পরিচয়ের নথি এবং এই চ্যাটে দেওয়া সংশোধিত তথ্য থেকে তৈরি। অজানা বা নথিভুক্ত নয় এমন নাম অনুমান না করে স্পষ্টভাবে চিহ্নিত করা হয়েছে।',ancestralRoot:'পূর্বপুরুষের সূত্র',startingPoint:'নথিভুক্ত বংশধারার সূচনা',mainBranch:'প্রধান শাখা',primaryFocus:'প্রধান প্রদর্শন',secondBranch:'সম্পর্কিত শাখা',compactBranch:'সংক্ষিপ্ত শাখা',howToRead:'কীভাবে পড়বেন',guideTitle:'প্রতিটি কার্ড দেখে সহজেই বোঝা যাবে কে কার বংশধর।',guideParent:'সংযোগ রেখা',guideParentText:'কার্ডের উপরের রেখাটি সেই ব্যক্তির পিতৃ/পারিবারিক উৎস দেখায়।',guideSpouse:'স্বামী/স্ত্রী',guideSpouseText:'একই কার্ডে স্বামী/স্ত্রীর নাম দেখানো হয়েছে; একাধিক বিয়ে থাকলে আলাদা করে দেখানো হয়েছে।',guideGeneration:'প্রজন্মের রং',guideGenerationText:'একই স্তরের প্রজন্মের জন্য একই রং ব্যবহার করা হয়েছে।',footerText:'পারিবারিক বংশ পরিচয় • পারিবারিক মিলনমেলার জন্য তৈরি',showChildren:'সন্তান দেখুন',hideChildren:'সন্তান লুকান',generation:'প্রজন্ম',deceased:'মৃত্যুবরণ',noResults:'এই নামে কোনো সদস্য পাওয়া যায়নি।',branchTitleMain:'মোহাব্বত আলি মুনসির পরিবার',branchTitleSecondary:'আব্দুল্লাহ চামড়া পরিবার'}
};
