(() => {
  const $ = id => document.getElementById(id);
  const esc = (v='') => String(v).replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const clone = v => JSON.parse(JSON.stringify(v));
  const lang = () => document.documentElement.lang === 'bn' ? 'bn' : 'en';
  const cfg = () => window.FAMILY_BACKEND_CONFIG || {};
  const ready = () => !!(cfg().enabled && cfg().supabaseUrl && cfg().supabaseAnonKey);
  const SNAP = 'familyTreeCloudSnapshot';
  const LOCAL = 'familyTreeV5Suggestions';
  let db = null, session = null, isAdmin = false, latest = null;

  const text = {
    en:{db:'Family Database',local:'Local mode',cloud:'Cloud connected',admin:'Admin connected',title:'Family Database V5',sub:'Shared corrections, private admin review, version history and approved photos.',overview:'Overview',submit:'Submit update',adminTab:'Admin',qr:'QR code',notConnected:'The shared database code is installed but Supabase has not been connected yet. The family tree still works normally.',connected:'The central family database is connected.',version:'Published version',setup:'To activate cloud mode, finish the steps in SUPABASE_SETUP.md and add the public project URL/key to backend-config.js.',send:'Send for review',person:'Family member',kind:'Update type',value:'Correct / new value',details:'Supporting details',name:'Your name (optional)',contact:'Contact (optional)',sent:'Submitted for family admin review.',saved:'Saved on this device until the shared database is connected.',claim:'This is me',nameEn:'English name',nameBn:'Bangla name',spouse:'Spouse',child:'Child',parents:'Father / Mother',birth:'Birth',death:'Death',location:'Location',occupation:'Occupation',story:'Family story / history',photo:'Photo URL / photo request',other:'Other',login:'Private admin login',email:'Admin email',magic:'Send secure magic link',magicSent:'Check your email for the sign-in link.',notAdmin:'This signed-in email is not on the family admin allow-list.',logout:'Sign out',seed:'Seed current tree',seedHelp:'Use this once after Supabase setup to create the first official cloud version.',edit:'Edit official person',publish:'Publish new version',add:'Add child / spouse',upload:'Upload approved photo',pending:'Pending submissions',history:'Version history',refresh:'Refresh',restore:'Restore',approve:'Approve + publish',mark:'Mark approved',reject:'Reject',open:'Open in editor',none:'None',noPending:'No pending submissions.',noHistory:'No cloud versions yet.',published:'New official family version published.',select:'Select a person',english:'English name',bangla:'Bangla name',notes:'Publish note',son:'Son',daughter:'Daughter',spouseSimple:'Spouse',wifeBranch:'New wife / marriage branch',parent:'Parent / person',wifeNumber:'Wife branch number (optional)',file:'Image file',thisMe:'This is me',copy:'Copy link',print:'Print QR',qrHelp:'Use this QR code at the family gathering so relatives can open the tree immediately.'},
    bn:{db:'পারিবারিক ডেটাবেস',local:'লোকাল মোড',cloud:'ক্লাউড সংযুক্ত',admin:'অ্যাডমিন সংযুক্ত',title:'পারিবারিক ডেটাবেস V5',sub:'শেয়ার্ড সংশোধন, ব্যক্তিগত অ্যাডমিন পর্যালোচনা, সংস্করণ ইতিহাস ও অনুমোদিত ছবি।',overview:'সারসংক্ষেপ',submit:'তথ্য পাঠান',adminTab:'অ্যাডমিন',qr:'QR কোড',notConnected:'শেয়ার্ড ডেটাবেসের কোড ইনস্টল করা আছে, কিন্তু Supabase এখনো সংযুক্ত নয়। পারিবারিক বৃক্ষ স্বাভাবিকভাবেই কাজ করছে।',connected:'কেন্দ্রীয় পারিবারিক ডেটাবেস সংযুক্ত আছে।',version:'প্রকাশিত সংস্করণ',setup:'ক্লাউড মোড চালু করতে SUPABASE_SETUP.md-এর ধাপ শেষ করে backend-config.js-এ public project URL/key যোগ করুন।',send:'পর্যালোচনার জন্য পাঠান',person:'পরিবারের সদস্য',kind:'আপডেটের ধরন',value:'সঠিক / নতুন তথ্য',details:'সহায়ক বিবরণ',name:'আপনার নাম (ঐচ্ছিক)',contact:'যোগাযোগ (ঐচ্ছিক)',sent:'পারিবারিক অ্যাডমিন পর্যালোচনার জন্য পাঠানো হয়েছে।',saved:'শেয়ার্ড ডেটাবেস সংযুক্ত না হওয়া পর্যন্ত এই ডিভাইসে সংরক্ষিত হয়েছে।',claim:'এটি আমি',nameEn:'ইংরেজি নাম',nameBn:'বাংলা নাম',spouse:'স্বামী/স্ত্রী',child:'সন্তান',parents:'পিতা / মাতা',birth:'জন্ম',death:'মৃত্যু',location:'স্থান',occupation:'পেশা',story:'পারিবারিক গল্প / ইতিহাস',photo:'ছবির URL / ছবি অনুরোধ',other:'অন্যান্য',login:'ব্যক্তিগত অ্যাডমিন লগইন',email:'অ্যাডমিন ইমেইল',magic:'নিরাপদ ম্যাজিক লিংক পাঠান',magicSent:'সাইন-ইন লিংকের জন্য আপনার ইমেইল দেখুন।',notAdmin:'এই ইমেইল পারিবারিক অ্যাডমিন তালিকায় নেই।',logout:'সাইন আউট',seed:'বর্তমান বৃক্ষ ডেটাবেসে দিন',seedHelp:'Supabase সেটআপের পরে প্রথম অফিসিয়াল ক্লাউড সংস্করণ তৈরির জন্য একবার ব্যবহার করুন।',edit:'অফিসিয়াল সদস্য সম্পাদনা',publish:'নতুন সংস্করণ প্রকাশ',add:'সন্তান / স্বামী-স্ত্রী যোগ',upload:'অনুমোদিত ছবি আপলোড',pending:'অপেক্ষমাণ প্রস্তাব',history:'সংস্করণ ইতিহাস',refresh:'রিফ্রেশ',restore:'ফিরিয়ে আনুন',approve:'অনুমোদন + প্রকাশ',mark:'অনুমোদিত',reject:'বাতিল',open:'এডিটরে খুলুন',none:'কিছু নেই',noPending:'কোনো অপেক্ষমাণ প্রস্তাব নেই।',noHistory:'এখনো কোনো ক্লাউড সংস্করণ নেই।',published:'নতুন অফিসিয়াল পারিবারিক সংস্করণ প্রকাশিত হয়েছে।',select:'একজনকে নির্বাচন করুন',english:'ইংরেজি নাম',bangla:'বাংলা নাম',notes:'প্রকাশনা নোট',son:'ছেলে',daughter:'মেয়ে',spouseSimple:'স্বামী/স্ত্রী',wifeBranch:'নতুন স্ত্রী / বিবাহ শাখা',parent:'অভিভাবক / ব্যক্তি',wifeNumber:'স্ত্রী শাখা নম্বর (ঐচ্ছিক)',file:'ছবির ফাইল',thisMe:'এটি আমি',copy:'লিংক কপি',print:'QR প্রিন্ট',qrHelp:'পারিবারিক সমাবেশে এই QR কোড ব্যবহার করলে সবাই দ্রুত বৃক্ষ খুলতে পারবে।'}
  };
  const t = k => text[lang()][k] || k;
  function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800);}

  function root(data=familyData){
    const n=data.rootTrail?.find(p=>p.id==='nayeb-chowdhury')||data.rootTrail?.find(p=>p.id==='nayer-chowdhury')||data.rootTrail?.[0];
    const c=data.rootTrail?.find(p=>p.id==='chan-gazi-hawladar')||data.rootTrail?.[1];
    return n&&c?{...n,children:[{...c,children:[data.main,data.secondary]}]}:null;
  }
  const children = p => [...(p?.children||[]),...(p?.spouseGroups||[]).flatMap(g=>g.children||[])];
  function people(data=familyData){const out=[],seen=new Set();const walk=p=>{if(!p?.id||seen.has(p.id))return;seen.add(p.id);out.push(p);children(p).forEach(walk);};walk(root(data));return out;}
  function options(selected=''){return people().map(p=>`<option value="${esc(p.id)}"${p.id===selected?' selected':''}>${esc(lang()==='bn'?(p.bn||p.en):(p.en||p.bn))}</option>`).join('');}
  function find(data,id){let hit=null;const walk=p=>{if(hit||!p)return;if(p.id===id){hit=p;return;}(p.children||[]).forEach(walk);(p.spouseGroups||[]).forEach(g=>(g.children||[]).forEach(walk));};(data.rootTrail||[]).forEach(walk);walk(data.main);walk(data.secondary);return hit;}
  const slug = v => String(v||'person').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'person';

  async function sdk(){
    if(db||!ready())return db;
    try{
      const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
      db=mod.createClient(cfg().supabaseUrl,cfg().supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
      const res=await db.auth.getSession();session=res.data.session||null;if(session)await checkAdmin();
      db.auth.onAuthStateChange(async(_e,s)=>{session=s;isAdmin=false;if(s)await checkAdmin();status();if($('v5Modal')?.classList.contains('show'))render('admin');});
      return db;
    }catch(e){console.warn('Family cloud unavailable',e);return null;}
  }
  async function checkAdmin(){if(!db||!session)return false;const r=await db.from('family_admins').select('email').limit(1).maybeSingle();isAdmin=!r.error&&!!r.data;return isAdmin;}
  async function sync(){if(!ready())return;const client=await sdk();if(!client)return;const r=await client.from('family_snapshots').select('id,version,data,note,created_at').eq('is_published',true).order('version',{ascending:false}).limit(1).maybeSingle();if(r.error)return;latest=r.data||null;if(latest?.data&&String(window.__FAMILY_CLOUD_SNAPSHOT_VERSION__||'')!==String(latest.version)){localStorage.setItem(SNAP,JSON.stringify({version:latest.version,data:latest.data,created_at:latest.created_at}));const k=`familyV5Reload:${latest.version}`;if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,'1');location.reload();return;}}status();}

  function ui(){
    const dock=$('featureDock')||document.querySelector('.controls');if(!dock||$('cloudStatusBtn'))return;
    const s=document.createElement('button');s.id='cloudStatusBtn';s.className='cloud-status-btn';s.type='button';s.onclick=()=>open('overview');dock.appendChild(s);
    const u=document.createElement('button');u.className='feature-btn';u.type='button';u.textContent=t('submit');u.onclick=()=>open('submit');dock.appendChild(u);
    const q=document.createElement('button');q.className='feature-btn';q.type='button';q.textContent=t('qr');q.onclick=()=>open('qr');dock.appendChild(q);
    document.body.insertAdjacentHTML('beforeend','<div id="v5Backdrop" class="v5-modal-backdrop"></div><section id="v5Modal" class="v5-modal" aria-hidden="true"><div class="v5-head"><div><h2></h2><p></p></div><button id="v5Close" class="v5-close">×</button></div><div id="v5Body" class="v5-body"></div></section>');
    $('v5Backdrop').onclick=close;$('v5Close').onclick=close;new MutationObserver(profileButtons).observe($('profileContent'),{childList:true,subtree:true});profileButtons();status();
  }
  function status(){const b=$('cloudStatusBtn');if(!b)return;b.classList.toggle('connected',ready());b.classList.toggle('admin',isAdmin);b.textContent=isAdmin?t('admin'):(ready()?t('cloud'):t('local'));}
  function close(){$('v5Backdrop')?.classList.remove('show');$('v5Modal')?.classList.remove('show');}
  function open(tab='overview',person=''){const m=$('v5Modal');m.querySelector('h2').textContent=t('title');m.querySelector('p').textContent=t('sub');$('v5Backdrop').classList.add('show');m.classList.add('show');render(tab,person);}
  function tabs(active){return `<div class="v5-tabs">${[['overview',t('overview')],['submit',t('submit')],['admin',t('adminTab')],['qr',t('qr')]].map(x=>`<button class="v5-tab${x[0]===active?' active':''}" data-tab="${x[0]}">${esc(x[1])}</button>`).join('')}</div><div id="v5Panel"></div>`;}
  async function render(tab,person=''){const body=$('v5Body');body.innerHTML=tabs(tab);body.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));if(tab==='overview')overview();if(tab==='submit')submit(person);if(tab==='qr')qr();if(tab==='admin')await adminPanel();}
  function overview(){const p=$('v5Panel');p.innerHTML=`<div class="v5-banner ${ready()?'good':'warn'}">${esc(ready()?t('connected'):t('notConnected'))}</div><div class="v5-grid"><div class="v5-card"><h3>${esc(t('version'))}</h3><p class="v5-code">${esc(String(latest?.version||window.__FAMILY_CLOUD_SNAPSHOT_VERSION__||t('none')))}</p></div><div class="v5-card"><h3>${esc(t('db'))}</h3><p>${esc(t('setup'))}</p></div></div>`;}
  const kinds=()=>[['claim',t('claim')],['name_en',t('nameEn')],['name_bn',t('nameBn')],['spouse',t('spouse')],['child',t('child')],['parents',t('parents')],['birth',t('birth')],['death',t('death')],['location',t('location')],['occupation',t('occupation')],['story',t('story')],['photo',t('photo')],['other',t('other')]];
  function submit(selected=''){const p=$('v5Panel');p.innerHTML=`<div class="v5-card"><form id="v5Submit" class="v5-form"><label>${esc(t('person'))}<select name="person"><option value="">${esc(t('select'))}</option>${options(selected)}</select></label><label>${esc(t('kind'))}<select name="kind">${kinds().map(x=>`<option value="${x[0]}">${esc(x[1])}</option>`).join('')}</select></label><label>${esc(t('value'))}<input name="value"></label><label>${esc(t('details'))}<textarea name="details" required></textarea></label><div class="v5-row"><label>${esc(t('name'))}<input name="name"></label><label>${esc(t('contact'))}<input name="contact"></label></div><button class="v5-btn primary">${esc(t('send'))}</button></form></div>`;$('v5Submit').onsubmit=sendUpdate;}
  async function sendUpdate(e){e.preventDefault();const f=new FormData(e.currentTarget),row={person_id:String(f.get('person')||'')||null,kind:String(f.get('kind')||'other'),details:String(f.get('details')||'').trim(),payload:{value:String(f.get('value')||'').trim(),language:lang()},submitter_name:String(f.get('name')||'').trim()||null,submitter_contact:String(f.get('contact')||'').trim()||null,status:'pending'};if(ready()){const client=await sdk();const r=client&&await client.from('family_submissions').insert(row);if(r&&!r.error){toast(t('sent'));e.currentTarget.reset();return;}}const list=JSON.parse(localStorage.getItem(LOCAL)||'[]');list.push({...row,id:`local-${Date.now()}`,created_at:new Date().toISOString()});localStorage.setItem(LOCAL,JSON.stringify(list));toast(t('saved'));e.currentTarget.reset();}

  async function adminPanel(){const p=$('v5Panel');if(!ready()){p.innerHTML=`<div class="v5-banner warn">${esc(t('notConnected'))}</div>`;return;}const client=await sdk();if(!client)return;const s=await client.auth.getSession();session=s.data.session||null;if(!session){p.innerHTML=`<div class="v5-card"><h3>${esc(t('login'))}</h3><form id="v5Login" class="v5-form"><label>${esc(t('email'))}<input type="email" name="email" required></label><button class="v5-btn primary">${esc(t('magic'))}</button></form></div>`;$('v5Login').onsubmit=magic;return;}await checkAdmin();status();if(!isAdmin){p.innerHTML=`<div class="v5-banner warn">${esc(t('notAdmin'))}</div><button id="v5Logout" class="v5-btn">${esc(t('logout'))}</button>`;$('v5Logout').onclick=logout;return;}p.innerHTML=`<div class="v5-actions"><button id="v5Seed" class="v5-btn success">${esc(t('seed'))}</button><button id="v5Refresh" class="v5-btn">${esc(t('refresh'))}</button><button id="v5Logout" class="v5-btn">${esc(t('logout'))}</button></div><p class="v5-banner">${esc(t('seedHelp'))}</p>${editHtml()}${addHtml()}${photoHtml()}<div class="v5-grid"><div class="v5-card"><h3>${esc(t('pending'))}</h3><div id="v5Pending" class="v5-list"></div></div><div class="v5-card"><h3>${esc(t('history'))}</h3><div id="v5History" class="v5-list"></div></div></div>`;$('v5Seed').onclick=()=>publish(clone(familyData),'Initial central family tree seed');$('v5Refresh').onclick=()=>adminPanel();$('v5Logout').onclick=logout;bindEdit();$('v5Add').onsubmit=addMember;$('v5Photo').onsubmit=uploadPhoto;await lists();}
  async function magic(e){e.preventDefault();const email=new FormData(e.currentTarget).get('email');const r=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});toast(r.error?r.error.message:t('magicSent'));}
  async function logout(){await db.auth.signOut();session=null;isAdmin=false;status();adminPanel();}

  function editHtml(){return `<div class="v5-card"><h3>${esc(t('edit'))}</h3><form id="v5Edit" class="v5-form"><label>${esc(t('person'))}<select name="id"><option value="">${esc(t('select'))}</option>${options()}</select></label><div class="v5-row"><label>${esc(t('english'))}<input name="en"></label><label>${esc(t('bangla'))}<input name="bn"></label></div><div class="v5-row"><label>${esc(t('birth'))}<input name="birth"></label><label>${esc(t('death'))}<input name="death"></label></div><div class="v5-row"><label>${esc(t('location'))} EN<input name="locationEn"></label><label>${esc(t('location'))} বাংলা<input name="locationBn"></label></div><div class="v5-row"><label>${esc(t('occupation'))} EN<input name="occupationEn"></label><label>${esc(t('occupation'))} বাংলা<input name="occupationBn"></label></div><div class="v5-row"><label>Story EN<textarea name="storyEn"></textarea></label><label>Story বাংলা<textarea name="storyBn"></textarea></label></div><label>${esc(t('notes'))}<input name="note"></label><button class="v5-btn primary">${esc(t('publish'))}</button></form></div>`;}
  function bindEdit(){const f=$('v5Edit');f.elements.id.onchange=()=>fill(f.elements.id.value);f.onsubmit=saveEdit;}
  function fill(id){const p=find(familyData,id),f=$('v5Edit');if(!p)return;['en','bn','birth','death','locationEn','locationBn','occupationEn','occupationBn','storyEn','storyBn'].forEach(k=>f.elements[k].value=p[k]||'');}
  async function saveEdit(e){e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get('id')||'');if(!id)return;const data=await current(),p=find(data,id);if(!p)return;['en','bn','birth','death','locationEn','locationBn','occupationEn','occupationBn','storyEn','storyBn'].forEach(k=>{const v=String(f.get(k)||'').trim();if(v)p[k]=v;else delete p[k];});await publish(data,String(f.get('note')||`Edit ${id}`));}

  function addHtml(){return `<div class="v5-card"><h3>${esc(t('add'))}</h3><form id="v5Add" class="v5-form"><div class="v5-row"><label>${esc(t('parent'))}<select name="parent"><option value="">${esc(t('select'))}</option>${options()}</select></label><label>Type<select name="type"><option value="son">${esc(t('son'))}</option><option value="daughter">${esc(t('daughter'))}</option><option value="spouse">${esc(t('spouseSimple'))}</option><option value="wife">${esc(t('wifeBranch'))}</option></select></label></div><div class="v5-row"><label>${esc(t('english'))}<input name="en" required></label><label>${esc(t('bangla'))}<input name="bn"></label></div><label>${esc(t('wifeNumber'))}<input name="branch" type="number" min="1"></label><label>${esc(t('notes'))}<input name="note"></label><button class="v5-btn primary">${esc(t('publish'))}</button></form></div>`;}
  async function addMember(e){e.preventDefault();const f=new FormData(e.currentTarget),parent=String(f.get('parent')||''),type=String(f.get('type')||''),en=String(f.get('en')||'').trim(),bn=String(f.get('bn')||'').trim();if(!parent||!en)return;const data=await current(),p=find(data,parent);if(!p)return;if(type==='spouse'){p.spouses=p.spouses||[];p.spouses.push({en,bn});}else if(type==='wife'){p.spouseGroups=p.spouseGroups||[];p.spouseGroups.push({spouseEn:en,spouseBn:bn,children:[]});}else{const child={id:`${slug(en)}-${Date.now().toString(36)}`,en,bn};if(type==='daughter'){child.relationEn='Daughter';child.relationBn='মেয়ে';}const n=Number(f.get('branch')||0);if(n&&p.spouseGroups?.[n-1])p.spouseGroups[n-1].children.push(child);else{p.children=p.children||[];p.children.push(child);}}await publish(data,String(f.get('note')||`Add ${en}`));}

  function photoHtml(){return `<div class="v5-card"><h3>${esc(t('upload'))}</h3><form id="v5Photo" class="v5-form"><label>${esc(t('person'))}<select name="person"><option value="">${esc(t('select'))}</option>${options()}</select></label><label>${esc(t('file'))}<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/heic" required></label><label>${esc(t('notes'))}<input name="note"></label><button class="v5-btn primary">${esc(t('upload'))}</button></form></div>`;}
  async function uploadPhoto(e){e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get('person')||''),file=f.get('file');if(!id||!(file instanceof File))return;const path=`${id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`,up=await db.storage.from('family-media').upload(path,file,{contentType:file.type});if(up.error){toast(up.error.message);return;}const pub=db.storage.from('family-media').getPublicUrl(path).data.publicUrl,data=await current(),p=find(data,id);p.photoUrl=pub;await publish(data,String(f.get('note')||`Photo for ${id}`));}

  async function current(){if(latest?.data)return clone(latest.data);const r=await db.from('family_snapshots').select('id,version,data').eq('is_published',true).order('version',{ascending:false}).limit(1).maybeSingle();if(r.data){latest=r.data;return clone(r.data.data);}return clone(familyData);}
  async function publish(data,note){const r=await db.from('family_snapshots').insert({data,note,is_published:true}).select('id,version,data,created_at').single();if(r.error){toast(r.error.message);return null;}await db.from('family_snapshots').update({is_published:false}).eq('is_published',true).neq('id',r.data.id);await db.from('family_audit_log').insert({action:'publish_snapshot',entity_type:'family_snapshot',entity_id:r.data.id,after_data:{version:r.data.version,note}});latest=r.data;localStorage.setItem(SNAP,JSON.stringify({version:r.data.version,data:r.data.data,created_at:r.data.created_at}));toast(t('published'));setTimeout(()=>location.reload(),600);return r.data;}

  async function lists(){const a=await db.from('family_submissions').select('*').eq('status','pending').order('created_at',{ascending:false}).limit(50),h=await db.from('family_snapshots').select('id,version,note,created_at,is_published').order('version',{ascending:false}).limit(30),subs=a.data||[],hist=h.data||[];$('v5Pending').innerHTML=subs.length?subs.map(s=>`<div class="v5-item"><b>${esc(s.kind)} · ${esc(s.person_id||'General')}</b><small>${esc(new Date(s.created_at).toLocaleString())}</small><p>${esc(s.payload?.value||'')}${s.payload?.value?'\n':''}${esc(s.details||'')}</p><div class="v5-actions">${auto(s)?`<button class="v5-btn success" data-auto="${s.id}">${esc(t('approve'))}</button>`:''}<button class="v5-btn" data-open="${esc(s.person_id||'')}">${esc(t('open'))}</button><button class="v5-btn" data-mark="${s.id}">${esc(t('mark'))}</button><button class="v5-btn danger" data-reject="${s.id}">${esc(t('reject'))}</button></div></div>`).join(''):`<p>${esc(t('noPending'))}</p>`;$('v5History').innerHTML=hist.length?hist.map(v=>`<div class="v5-item"><b>Version ${v.version}</b> ${v.is_published?'<span class="v5-pill approved">published</span>':''}<small>${esc(new Date(v.created_at).toLocaleString())}</small><p>${esc(v.note||'')}</p><button class="v5-btn" data-restore="${v.id}">${esc(t('restore'))}</button></div>`).join(''):`<p>${esc(t('noHistory'))}</p>`;document.querySelectorAll('[data-auto]').forEach(b=>b.onclick=()=>approveAuto(subs.find(x=>x.id===b.dataset.auto)));document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>review(b.dataset.mark,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>review(b.dataset.reject,'rejected'));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(!b.dataset.open)return;const f=$('v5Edit');f.elements.id.value=b.dataset.open;fill(b.dataset.open);f.scrollIntoView({behavior:'smooth'});});document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>restore(b.dataset.restore));}
  function auto(s){return s?.person_id&&s?.payload?.value&&['name_en','name_bn','birth','death','location','occupation','story','photo'].includes(s.kind);}
  async function approveAuto(s){if(!auto(s))return;const data=await current(),p=find(data,s.person_id),v=String(s.payload.value||'').trim(),bn=s.payload.language==='bn',map={name_en:'en',name_bn:'bn',birth:'birth',death:'death',location:bn?'locationBn':'locationEn',occupation:bn?'occupationBn':'occupationEn',story:bn?'storyBn':'storyEn',photo:'photoUrl'};p[map[s.kind]]=v;const row=await publish(data,`Approved submission ${s.id}: ${s.kind}`);if(row)await review(s.id,'approved');}
  async function review(id,statusValue){await db.from('family_submissions').update({status:statusValue,reviewed_at:new Date().toISOString(),reviewed_by:session?.user?.id||null}).eq('id',id);await db.from('family_audit_log').insert({action:`submission_${statusValue}`,entity_type:'family_submission',entity_id:id});await lists();}
  async function restore(id){const r=await db.from('family_snapshots').select('data,version').eq('id',id).single();if(r.data)await publish(clone(r.data.data),`Restore version ${r.data.version}`);}

  async function qr(){const p=$('v5Panel'),url=location.origin+location.pathname;p.innerHTML=`<div class="v5-card v5-qr"><canvas id="v5Qr" width="280" height="280"></canvas><p>${esc(t('qrHelp'))}</p><div class="v5-code">${esc(url)}</div><div class="v5-actions"><button id="v5Copy" class="v5-btn primary">${esc(t('copy'))}</button><button id="v5Print" class="v5-btn">${esc(t('print'))}</button></div></div>`;$('v5Copy').onclick=()=>navigator.clipboard?.writeText(url);$('v5Print').onclick=()=>window.print();try{const mod=await import('https://cdn.jsdelivr.net/npm/qrcode@1.5.4/+esm'),q=mod.default||mod;await q.toCanvas($('v5Qr'),url,{width:280,margin:2});}catch(_){const c=$('v5Qr'),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,280,280);x.fillStyle='#173a63';x.textAlign='center';x.font='14px sans-serif';x.fillText('Use the link below',140,145);}}
  function profileButtons(){const c=$('profileContent');if(!c||c.querySelector('.profile-v5-actions'))return;const f=c.querySelector('[data-focus-person]');if(!f)return;const id=f.dataset.focusPerson,w=document.createElement('div');w.className='profile-v5-actions';w.innerHTML=`<button>${esc(t('thisMe'))}</button><button>${esc(t('submit'))}</button><button>${esc(t('db'))}</button>`;c.querySelector('.profile-actions')?.before(w);w.children[0].onclick=()=>{open('submit',id);setTimeout(()=>{$('v5Submit').elements.kind.value='claim';},0);};w.children[1].onclick=()=>open('submit',id);w.children[2].onclick=()=>open('overview');}
  async function boot(){ui();await sdk();await sync();status();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
